  - name: Install Base Require Software In Redhat Client
    yum: name=bzr state=latest
    when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
  - name: Download Tpcc Software To Redhat Client
    shell: "cd /tmp ; bzr branch lp:~percona-dev/perconatools/tpcc-mysql"
    when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
  - name: Compile Tpcc Software To Redhat Client
    shell: "cd /tmp/tpcc-mysql/src; make"
    when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
  - name: Create Mysql Tpcc Database In Redhat Client
    shell: mysql -h {{ ansible_default_ipv4.address }} -u {{ mysql_database_user }} -p{{ mysql_passwd }}  -e "{{ item }}"
    with_items:
      - create database tpcc100;
    when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
  - name: Load  Mysql Tpcc Data Table In Redhat Client
    shell: mysql -h {{ ansible_default_ipv4.address }} -u {{ mysql_database_user }} -p{{ mysql_passwd }} {{ tpcc_database_name }} </tmp/tpcc-mysql/{{ item }}
    with_items:
      - create_table.sql
      - add_fkey_idx.sql
    when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
  - name: Create Tpcc Mysql Test Data To Redhat Client
    shell: /tmp/tpcc-mysql/tpcc_load {{ ansible_default_ipv4.address }} {{ tpcc_database_name }} {{ mysql_database_user }} {{ mysql_passwd }} {{ warehouse }}
    when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
  - name: Start Mysql Tpcc Test In  Redhat Client
    shell: /tmp/tpcc-mysql/tpcc_start -h {{ ansible_default_ipv4.address }} -u {{ mysql_database_user }} -p{{ mysql_passwd }} -d {{ tpcc_database_name }} -w {{ w }} -c {{ c }} -r {{ r }} -l {{ l }} -f {{ f }} > /tmp/tpcc-mysql/{{ f }}.log
    when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
    tags: Onlytest
  - name: Copy Mysql Tpcc Result from Redhat Client
    fetch: src=/tmp/tpcc-mysql/{{ f }}.log dest=/tmp/mysql-tpcc-{{ ansible_default_ipv4.address }}.log flat=yes
    when: ansible_os_family == "RedHat" and ansible_distribution_version|int >=6
    tags: Onlytest
